name: Unit Tests

on:
  push:
    branches: 
      - main
    
jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
      
      - name: Lint project
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test:build
